### ISSUE TITLE
document how to compile on linux

### ISSUE THREAD

**Issue by kindlychung** [krystiankaluzny/Tanks#1]

**Comment by krystiankaluzny** [comment]
Tank is my end of semester project and it had to eventually work on Windows but the first version was developed on linux. If you wonder how to build linux version try to revert changes from commit [02596c84c7e66797217186a5532a078f2d17026c](https://github.com/krystiankaluzny/Tanks/commit/02596c84c7e66797217186a5532a078f2d17026c#diff-b67911656ef5d18c4ae36cb6741b7965) that was make in Makefile. 

Soon I will try to rewrite the Makefile so that it would be OS agnostic.

**Comment by kindlychung** [comment]
Yeah, it works once i start it up from the pwd of the binary. 
Very nice work, man. Brings back a lot of childhood memory. Thanks!

**Comment by krystiankaluzny** [comment]
To be more complete, I have added [build on windows section](https://github.com/krystiankaluzny/Tanks#windows)
